# Generated by Django 2.2.2 on 2019-06-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtask',
            name='state',
            field=models.IntegerField(choices=[(1, '运行中'), (2, '成功'), (3, '失败')], default=1),
        ),
        migrations.AddField(
            model_name='etltask',
            name='state',
            field=models.IntegerField(choices=[(1, '运行中'), (2, '成功'), (3, '失败')], default=1),
        ),
    ]
