# Generated by Django 2.2.2 on 2019-06-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190625_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtask',
            name='step',
            field=models.IntegerField(default=1),
        ),
    ]
