# Generated by Django 2.2.2 on 2019-06-26 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20190626_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtask',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='etltask',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
