# Generated by Django 2.2.2 on 2019-06-28 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20190626_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='finished_at',
        ),
        migrations.AddField(
            model_name='app',
            name='input_dir',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='app',
            name='output_dir',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='buildingtask',
            name='state',
            field=models.IntegerField(choices=[(1, '进行中'), (2, '成功'), (3, '失败')], default=1),
        ),
        migrations.AlterField(
            model_name='etltask',
            name='state',
            field=models.IntegerField(choices=[(1, '进行中'), (2, '成功'), (3, '失败')], default=1),
        ),
    ]
