# Generated by Django 2.2.2 on 2019-06-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20190628_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingtask',
            name='ks',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
