#%RAML 1.0

title: GNS 接口文档
version: 1.0.0
baseUri: http://gns.tslow.cn


/tasks/apps/:
  displayName: 获取应用列表
  get:
    description: 获取应用列表
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "data": [{
                          "id": 2,
                          "name": "现金分期营销应用",
                          "percent": 0,
                          "project": null,
                          "status": "就绪"
                      },
                      {
                          "id": 1,
                          "name": "借转贷应用",
                          "percent": 81,
                          "project": {
                              "app_id": 1,
                              "buildingtasks": [{
                                      "created_at": "2019-06-26 06:57:12.252980+00:00",
                                      "dist": "2019-06-26 06:56:45_1.txt",
                                      "duration": 10,
                                      "finished_at": "2019-06-26 06:57:22.260989+00:00",
                                      "id": 13,
                                      "info": "",
                                      "ks": null,
                                      "name": "响应模型",
                                      "project_id": 33,
                                      "state": 2,
                                      "status": "成功",
                                      "step": 1,
                                      "target": "C:\\output\\result1\\"
                                  },
                                  {
                                      "created_at": "2019-06-26 06:57:22.269960+00:00",
                                      "dist": "",
                                      "duration": 4,
                                      "finished_at": null,
                                      "id": 14,
                                      "info": "",
                                      "ks": null,
                                      "name": "逾期模型",
                                      "project_id": 33,
                                      "state": 1,
                                      "status": "运行中",
                                      "step": 2,
                                      "target": ""
                                  }
                              ],
                              "created_at": "2019-06-26 06:56:45.486986+00:00",
                              "duration": 41,
                              "etltasks": [{
                                      "created_at": "2019-06-26 06:56:45.499988+00:00",
                                      "duration": 6,
                                      "finished_at": "2019-06-26 06:56:51.505005+00:00",
                                      "id": 20,
                                      "info": "",
                                      "name": "数据处理到数据库中",
                                      "project_id": 33,
                                      "state": 2,
                                      "status": "成功",
                                      "step": 1
                                  },
                                  {
                                      "created_at": "2019-06-26 06:57:02.234967+00:00",
                                      "duration": 10,
                                      "finished_at": "2019-06-26 06:57:12.243989+00:00",
                                      "id": 21,
                                      "info": "",
                                      "name": "将分散数据表拼成宽表",
                                      "project_id": 33,
                                      "state": 2,
                                      "status": "成功",
                                      "step": 2
                                  }
                              ],
                              "finished_at": null,
                              "id": 33,
                              "name": "2019-06-26 06:56:45",
                              "percent": 81,
                              "status": "逾期模型生成中"
                          },
                          "status": "逾期模型生成中"
                      }
                  ]
              }


/tasks/etltasks/:
  displayName: 获取所有ETL任务列表
  get:
    description: 获取所有ETL任务列表
    queryParameters:
      app_id:
      name:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "data": [
                  {
                    "id": 15,
                    "info": "",
                    "name": "宽表生成任务",
                    "project_id": 30,
                    "state": 2,
                    "status": "成功",
                    "step": 2,
                    "project_name": "2019-06-25 13:16:49",
                    "app_name": "借转贷应用",
                    "app_id": 1
                  }
                ]
              }


/tasks/buildingtasks/:
  displayName: 获取所有建模任务列表
  get:
    description: 获取所有建模任务列表
    queryParameters:
      app_id:
      name:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "data": [
                  {
                    "dist": "2019-06-25 13:16:49_2.txt",
                    "id": 8,
                    "info": "",
                    "name": "逾期模型",
                    "project_id": 30,
                    "state": 2,
                    "status": "成功",
                    "step": 2,
                    "target": "C:/output/result2/",
                    "project_name": "2019-06-25 13:16:49",
                    "app_name": "借转贷应用",
                    "app_id": 1
                  }
                ]
              }


/tasks/apps/{app_id}/dir/:
  displayName: 应用目录配置
  get:
    description: 获取应用目录信息
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "input_dir": "D:\\workspace\\gnsbackend\\input",
                  "input_exists": true,
                  "output_dir": "D:\\workspace\\gnsbackend\\output",
                  "output_exists": false
              }
  post:
    description: 设置应用输入和输出目录
    body:
      multipart/form-data:
        properties:
          input_dir:
          output_dir:
    responses:
      200:
        body:
          application/json:
            example: |
              {
                  "input_dir": "D:\\workspace\\gnsbackend\\input",
                  "input_exists": true,
                  "output_dir": "D:\\workspace\\gnsbackend\\output",
                  "output_exists": false
              }


